[colors.bright]
black = "0x282a40"
blue = "0xa3c5ff"
cyan = "0x98fffd"
green = "0xe0ffad"
magenta = "0xd6afed"
red = "0xeb7f84"
white = "0xd1e5ed"
yellow = "0xffee7e"

[colors.normal]
black = "0x181a29"
blue = "0x93bbff"
cyan = "0x98e4ff"
green = "0xcdea9f"
magenta = "0xd3a7ee"
red = "0xF07178"
white = "0xbfd5de"
yellow = "0xffd47e"

[colors.primary]
background = "0x212121"
foreground = "0xc5c9de"

[font]
size = 13

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "None"
opacity = 0.9
startup_mode = "Fullscreen"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
